#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

AUTOGEN_RE = re.compile(
    r"(?s)(<!--\s*AUTOGEN:(?P<key>[A-Z0-9_-]+):START\s*-->)(.*?)(<!--\s*AUTOGEN:(?P=key):END\s*-->)"
)


def run(cmd: list[str], cwd: Path) -> str:
    p = subprocess.run(cmd, cwd=str(cwd), stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if p.returncode != 0:
        return ""
    return p.stdout.strip()


def repo_root_from(script_dir: Path) -> Path:
    # Prefer git
    root = run(["git", "rev-parse", "--show-toplevel"], cwd=script_dir)
    if root:
        return Path(root)

    # Fallback: walk upwards looking for .git
    for p in [script_dir, *script_dir.parents]:
        if (p / ".git").exists():
            return p

    # Last resort: repo/.claude/skills/manage-project/scripts
    return script_dir.parents[4]


def choose_includes(repo_root: Path, user_includes: list[str]) -> list[str]:
    if user_includes:
        return user_includes

    # Common code/doc roots across projects
    candidates = ["src", "app", "main", "project", "docs", "packages"]
    existing = [c for c in candidates if (repo_root / c).exists()]
    return existing if existing else ["."]


def scan_todos(repo_root: Path, includes: list[str], limit: int) -> tuple[int, int, list[str]]:
    scan = Path(__file__).resolve().parent / "scan_todos.py"
    if not scan.exists():
        return (0, 0, [])

    cmd = [str(scan), str(repo_root)]
    for inc in includes:
        cmd += ["--include", inc]
    cmd += ["--limit", str(limit)]

    out = run(cmd, cwd=repo_root)
    if not out:
        return (0, 0, [])

    lines = out.splitlines()
    header = lines[0]
    m_todo = re.search(r"TODO=(\d+)", header)
    m_fixme = re.search(r"FIXME=(\d+)", header)
    todo = int(m_todo.group(1)) if m_todo else 0
    fixme = int(m_fixme.group(1)) if m_fixme else 0

    items: list[str] = []
    for line in lines[1:]:
        parts = line.split("\t", 2)
        if len(parts) != 3:
            continue
        kind, loc, text = parts
        items.append(f"- **{kind}** `{loc}` — {text}")

    return (todo, fixme, items)


def replace_autogen(text: str, replacements: dict[str, str]) -> str:
    def repl(m: re.Match[str]) -> str:
        key = m.group("key")
        start = m.group(1)
        end = m.group(4)
        body = replacements.get(key, m.group(3))
        return f"{start}\n{body}\n{end}"

    return AUTOGEN_RE.sub(repl, text)


TODO_TEMPLATE = """# Todo

## Backlog

<!-- AUTOGEN:DISCOVERED_TASKS:START -->
_Generated by manage-project/scripts/update_autogen.py_
<!-- AUTOGEN:DISCOVERED_TASKS:END -->
"""

STATUS_TEMPLATE = """# Project Status

## Summary

(Hand-written summary goes here.)

<!-- AUTOGEN:PROJECT_SNAPSHOT:START -->
_Generated by manage-project/scripts/update_autogen.py_
<!-- AUTOGEN:PROJECT_SNAPSHOT:END -->
"""


def ensure_file(path: Path, content: str, init: bool) -> bool:
    if path.exists():
        return True
    if not init:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> None:
    ap = argparse.ArgumentParser(description="Update AUTOGEN blocks in project docs")
    ap.add_argument("--root", default=".", help="Repository root (default: current dir)")
    ap.add_argument("--include", action="append", default=[], help="Subpaths to scan for TODO/FIXME (repeatable)")
    ap.add_argument("--limit", type=int, default=80, help="Max TODO/FIXME items to include")
    ap.add_argument("--todo", default="project/todo.md", help="Todo file path (relative to root)")
    ap.add_argument("--status", default="project/project-status.md", help="Status file path (relative to root)")
    ap.add_argument("--init", action="store_true", help="Create missing project files with AUTOGEN blocks")
    args = ap.parse_args()

    script_dir = Path(__file__).resolve().parent
    repo_root = Path(args.root).resolve() if args.root != "." else repo_root_from(script_dir)

    now = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M:%S %z")

    branch = run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=repo_root) or "(unknown)"
    head = run(["git", "rev-parse", "--short", "HEAD"], cwd=repo_root) or "(unknown)"
    recent = run(["git", "--no-pager", "log", "--oneline", "-n", "5"], cwd=repo_root)
    status = run(["git", "--no-pager", "status", "--porcelain=v1"], cwd=repo_root)

    includes = choose_includes(repo_root, args.include)
    todo_count, fixme_count, todo_items = scan_todos(repo_root, includes=includes, limit=args.limit)

    discovered_block = "\n".join(
        [
            f"_Generated at: {now}_",
            "",
            f"- Scanned: {', '.join(includes)}",
            f"- Totals: TODO={todo_count}, FIXME={fixme_count}",
            "",
            f"### Top TODO/FIXME occurrences (first {args.limit})",
            *todo_items,
        ]
    )

    snapshot_block = "\n".join(
        [
            f"_Generated at: {now}_",
            "",
            f"- Git branch: `{branch}`",
            f"- Git HEAD: `{head}`",
            f"- TODO/FIXME in repo: TODO={todo_count}, FIXME={fixme_count}",
            "",
            "### Recent commits (5)",
            "```",
            recent or "(no git history)",
            "```",
            "",
            "### Working tree (porcelain)",
            "```",
            status if status else "(clean)",
            "```",
        ]
    )

    todo_path = repo_root / args.todo
    status_path = repo_root / args.status

    updated: list[Path] = []

    if ensure_file(todo_path, TODO_TEMPLATE, init=args.init):
        todo_text = todo_path.read_text(encoding="utf-8")
        todo_text = replace_autogen(todo_text, {"DISCOVERED_TASKS": discovered_block})
        todo_path.write_text(todo_text, encoding="utf-8")
        updated.append(todo_path)
    else:
        print(f"Skip (missing): {todo_path}")

    if ensure_file(status_path, STATUS_TEMPLATE, init=args.init):
        ps_text = status_path.read_text(encoding="utf-8")
        ps_text = replace_autogen(ps_text, {"PROJECT_SNAPSHOT": snapshot_block})
        status_path.write_text(ps_text, encoding="utf-8")
        updated.append(status_path)
    else:
        print(f"Skip (missing): {status_path}")

    if updated:
        print("Updated AUTOGEN blocks:")
        for p in updated:
            print(f"- {p}")
    else:
        print("Nothing updated.")


if __name__ == "__main__":
    main()
